name: "Validate no JSON5 files"

on:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  validate:
    runs-on: ubuntu-24.04
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: "Validate that the PR does not introduce .json5 files"
        run: .github/scripts/validate-no-json5.sh
